### ISSUE TITLE
Using Colab's GPU

### ISSUE THREAD

**Issue by Unco3892** [naru-T/RstudioServer_on_Colab#2]
Hi,

Thanks a lot for this great project. Do you think it would be possible to use the GPU of google colab on RStudio's interface through `tensorflow` and `keras` packages ? I cannot get the server to recognize the python's path and since we there is no root access, it's not possible to install it separately using miniconda. Do you see any way around this?

**Comment by Unco3892** [comment]
I have managed to solve this issue, if you run `reticulate::py_config()`, it will not initially detect the pre-installed python, however if you say no, then it'll automatically find it and run `tensorflow` using colab's GPU.

**Comment by naru-T** [comment]
Fantastic. Thanks @Unco3892 !
