### ISSUE TITLE
This has stopped working

### ISSUE THREAD

**Issue by quantitative-technologies** [naru-T/RstudioServer_on_Colab#3]
I was able to use this successfully before.

But now when I tried it again it fails on # 3. Launch Rstudio server with localtunnel

The code

```
!lt --port 8787 
```

never stops executing and no URL appears.

**Comment by naru-T** [comment]
@quantitative-technologies 

Thanks. 
It seems localtunnel yields an error.
Now I've replaced localtunnel with ngrok to access rstudio server properly.

**Comment by quantitative-technologies** [comment]
Awesome! I was actually wondering before how to do it with `ngrok` instead.

**Comment by quantitative-technologies** [comment]
Unfortunately, this has stopped working for me as of today. When I go to the rserver URL I get:

Failed to complete tunnel connection
The connection to https://b9e3-34-125-242-31.ngrok-free.app/ was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address [localhost:8787](http://localhost:8787/).

Make sure that a web service is running on [localhost:8787](http://localhost:8787/) and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:8787: connect: connection refused

**Comment by naru-T** [comment]
Now it's fixed by updating the Rstudio server to 2023.06.1-524 !

**Comment by quantitative-technologies** [comment]
Actually, it started working for me again today without updating! :smile:  (Still using 2023.03.0 .)

**Comment by quantitative-technologies** [comment]
FYI, today I had to upgrade to make it work. Thanks for this info.
